logs:
    "2025-07-20":
        - Task: Initial project setup
          Time: "1h30m"

    "2025-08-06":
        - Task:
              - Fix git history (reset history, 'Initial commit' then only 'Update content')
              - Fix this file to comply with new format and same for projects active today
              - New file daily-projects.yaml, index of projects active given day
          Time: "1h20m"
